import { listEvents, createEvent, setCurrentEventId, getCurrentEventId, getEventInfo, saveEventInfo,
         getPeople, setPeople, getPrizes, getCurrentPrizeIdRemote, setCurrentPrizeIdRemote,
         getQuestions, setQuestions, getAssets, setAssets, getPolls, setPoll, upsertEventMeta } from './core_firebase.js';
import { addPrize, setCurrentPrize, drawBatch } from './stage_prizes_firebase.js';
import { handleImportCSV, loadRoster } from './roster_firebase.js';
const $=(s)=>document.querySelector(s);
function show(targetId){ document.querySelectorAll('.subpage').forEach(s=>s.style.display='none'); const sec=document.getElementById(targetId); if(sec) sec.style.display='block'; document.querySelectorAll('#cmsNav .nav-item').forEach(b=> b.classList.toggle('active', b.dataset.target===targetId)); }
async function renderEventList(){const list=await listEvents();const el=$('#eventList');if(!el)return;el.innerHTML='';list.forEach(ev=>{const item=document.createElement('div');item.className='event-item'+(getCurrentEventId()===ev.id?' active':'');item.innerHTML=`<div class="event-name">${ev.name}</div><div class="event-meta">ID: ${ev.id}</div>`;item.onclick=async()=>{setCurrentEventId(ev.id);await renderAll();};el.appendChild(item);});const ad=document.createElement('div');ad.className='sidebar-form';ad.innerHTML=`<input id="newEventName" placeholder="新增活動名稱" /><input id="newClientName" placeholder="客戶名稱" /><button id="btnAddEvent" class="btn primary">+ 新活動</button>`;el.appendChild(ad);ad.querySelector('#btnAddEvent').onclick=async()=>{const name=ad.querySelector('#newEventName').value.trim();const client=ad.querySelector('#newClientName').value.trim();const id=await createEvent(name,client);setCurrentEventId(id);await renderAll();};}
async function renderEventInfo(){const eid=getCurrentEventId();if(!eid)return;const {meta,info}=await getEventInfo(eid);const t=(id,val)=>{const e=document.getElementById(id);if(e)e.value=val||'';};t('evTitle',info.title);t('evClient',info.client);t('evDateTime',info.dateTime);t('evVenue',info.venue);t('evAddress',info.address);t('evMapUrl',info.mapUrl);t('evBus',info.bus);t('evTrain',info.train);t('evParking',info.parking);t('evNotes',info.notes);t('metaName',meta.name);t('metaClient',meta.client);document.getElementById('metaListed').checked=meta.listed!==false;}
function bindEventInfoSave(){document.getElementById('saveEventInfo')?.addEventListener('click',async()=>{const eid=getCurrentEventId();if(!eid)return;const g=id=>document.getElementById(id)?.value||'';await saveEventInfo(eid,{title:g('evTitle'),client:g('evClient'),dateTime:g('evDateTime'),venue:g('evVenue'),address:g('evAddress'),mapUrl:g('evMapUrl'),bus:g('evBus'),train:g('evTrain'),parking:g('evParking'),notes:g('evNotes')});await upsertEventMeta(eid,{name:g('metaName')||g('evTitle')||'新活動',client:g('metaClient'),listed:document.getElementById('metaListed').checked});await renderAll();});}
async function renderRoster(){const eid=getCurrentEventId();if(!eid)return;const people=await getPeople(eid);const root=document.getElementById('guestList');root.innerHTML='';const q=document.getElementById('searchGuest')?.value?.toLowerCase()||'';const list=people.filter(p=>(p.name||'').toLowerCase().includes(q)||(p.dept||'').toLowerCase().includes(q));list.forEach(p=>{const row=document.createElement('div');row.className='row';row.innerHTML=`<label><input type="checkbox" ${p.checkedIn?'checked':''}/> ${p.name} <small>${p.dept||''}</small></label>`;row.querySelector('input').onchange=async(e)=>{p.checkedIn=e.target.checked;await setPeople(eid,people);};root.appendChild(row);});document.getElementById('rosterCount').textContent=`共 ${people.length} 人`; }
function bindRoster(){document.getElementById('btnImportCSV')?.addEventListener('click',()=>{const f=document.getElementById('csvFile');if(!f?.files?.[0])return;handleImportCSV(f.files[0],async()=>{await renderRoster();});});document.getElementById('btnExportCSV')?.addEventListener('click',async()=>{const list=await loadRoster();const rows=[['Name','Dept','CheckedIn','Table','Seat'],...list.map(p=>[p.name,p.dept||'',p.checkedIn?1:0,p.table||'',p.seat||''])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));a.download='roster.csv';a.click();});document.getElementById('searchGuest')?.addEventListener('input',renderRoster);}
async function renderPrizes(){const eid=getCurrentEventId();if(!eid)return;const [prizes,curId]=await Promise.all([getPrizes(eid),getCurrentPrizeIdRemote(eid)]);const tbody=document.getElementById('prizeRows');tbody.innerHTML='';(prizes||[]).forEach(p=>{const used=(p.winners||[]).length;const tr=document.createElement('tr');tr.innerHTML=`<td><input type="radio" name="curpr" ${curId===p.id?'checked':''}></td><td>${p.name||''}</td><td>${p.quota||1}</td><td>${used}</td>`;tr.querySelector('input').onchange=async()=>{await setCurrentPrize(p.id);await renderPrizes();};tbody.appendChild(tr);});const wins=document.getElementById('winnersList');wins.innerHTML='';(prizes||[]).forEach(p=>(p.winners||[]).forEach(w=>{const li=document.createElement('li');li.textContent=`${w.name}（${p.name}）`;wins.appendChild(li);}));}
function bindPrizeActions(){document.getElementById('addPrize')?.addEventListener('click',async()=>{const name=document.getElementById('newPrizeName')?.value.trim();const q=Number(document.getElementById('newPrizeQuota')?.value||1);if(!name)return;await addPrize(name,q);await renderPrizes();});document.getElementById('drawBatch')?.addEventListener('click',async()=>{const n=Number(document.getElementById('batchCount')?.value||1);await drawBatch(n);await renderPrizes();});}
async function renderQuestions(){const list=await getQuestions(getCurrentEventId());const ul=document.getElementById('questionList');ul.innerHTML='';list.forEach(q=>{const li=document.createElement('li');li.textContent=q;ul.appendChild(li);});}
function bindQuestions(){document.getElementById('btnAddQuestion')?.addEventListener('click',async()=>{const eid=getCurrentEventId();const val=document.getElementById('newQuestion')?.value.trim();if(!val)return;const list=await getQuestions(eid);list.push(val);await setQuestions(eid,list);document.getElementById('newQuestion').value='';await renderQuestions();});}
async function renderAssets(){const a=await getAssets(getCurrentEventId());document.getElementById('bannerUrl').value=a.banner||'';document.getElementById('logoUrl').value=a.logo||'';const grid=document.getElementById('photosGrid');grid.innerHTML='';(a.photos||[]).forEach((url,idx)=>{const d=document.createElement('div');d.className='photo';d.innerHTML=`<img src="${url}" style="max-width:120px"><br><button data-i="${idx}" class="btn small">刪除</button>`;grid.appendChild(d);});grid.querySelectorAll('button').forEach(btn=>btn.onclick=async()=>{const i=Number(btn.dataset.i);const a2=await getAssets(getCurrentEventId());a2.photos.splice(i,1);await setAssets(getCurrentEventId(),a2);await renderAssets();});}
function bindAssets(){document.getElementById('saveAssets')?.addEventListener('click',async()=>{const eid=getCurrentEventId();const banner=document.getElementById('bannerUrl').value.trim();const logo=document.getElementById('logoUrl').value.trim();const cur=await getAssets(eid);await setAssets(eid,{...cur,banner,logo});await renderAssets();});document.getElementById('addPhoto')?.addEventListener('click',async()=>{const eid=getCurrentEventId();const url=prompt('貼上相片 URL');if(!url)return;const cur=await getAssets(eid);cur.photos=cur.photos||[];cur.photos.push(url.trim());await setAssets(eid,cur);await renderAssets();});}
async function renderPolls(){const polls=await getPolls(getCurrentEventId());const list=document.getElementById('pollList');list.innerHTML='';Object.values(polls||{}).forEach(p=>{const li=document.createElement('li');const total=Object.values(p.votes||{}).reduce((a,b)=>a+Number(b||0),0);li.innerHTML=`<strong>${p.question}</strong> <small>(共 ${total} 票)</small>`;list.appendChild(li);});}
function bindPolls(){document.getElementById('btnAddPoll')?.addEventListener('click',async()=>{const eid=getCurrentEventId();const q=document.getElementById('newPollQ').value.trim();const raw=document.getElementById('newPollOpts').value.trim();if(!q||!raw)return;const options=raw.split(/\n|,/).map(s=>s.trim()).filter(Boolean).map((t,i)=>({id:'o'+(i+1),text:t}));const poll={id:'poll'+Date.now().toString(36),question:q,options,votes:{}};await setPoll(eid,poll);document.getElementById('newPollQ').value='';document.getElementById('newPollOpts').value='';await renderPolls();});}
export async function renderAll(){await renderEventList();await renderEventInfo();await renderRoster();await renderPrizes();await renderQuestions();await renderAssets();await renderPolls();}
export async function bootCMS(){const u=new URL(location.href);const eid=u.searchParams.get('event');const list=await listEvents();if(eid&&list.some(e=>e.id===eid))setCurrentEventId(eid);else if(list[0])setCurrentEventId(list[0].id);document.querySelectorAll('#cmsNav .nav-item').forEach(b=> b.addEventListener('click',()=> show(b.dataset.target)));bindEventInfoSave();bindRoster();bindPrizeActions();bindQuestions();bindAssets();bindPolls();await renderAll();}